import { useState } from "react";
import { ArrowLeft, Copy, Search, ShieldCheck, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const statuses = ["ALL", "ACTIVE", "EXPIRED", "REVOKED", "DESTROYED"] as const;
export default function Dashboard() {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState<(typeof statuses)[number]>("ALL");
  const query = trpc.drops.dashboard.useQuery({ search: search || undefined, status });
  const revoke = trpc.drops.revoke.useMutation({ onSuccess: () => { query.refetch(); toast.success("Drop revoked", { description: "Ciphertext was deleted and the link is invalid." }); } });
  return <main className="dashboard-page"><div className="dashboard-inner"><div className="dashboard-nav"><Link href="/" className="back-link"><ArrowLeft size={16} /> New drop</Link><div className="object-label"><ShieldCheck size={14} /> SESSION LEDGER</div></div><div className="dashboard-head"><div><div className="eyebrow"><span className="eyebrow-dot" /> CURRENT BROWSER CONTEXT</div><h1>Your drops.</h1><p>Only drops created in this browser session appear here. The links continue to work for recipients even if you clear this cookie.</p></div><div className="dashboard-count"><strong>{query.data?.drops?.length ?? 0}</strong><span>entries found</span></div></div><div className="dashboard-controls"><div className="dashboard-search"><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search title or drop ID" /></div><div className="status-filters">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={status === item ? "selected" : ""}>{item}</button>)}</div></div><div className="dashboard-list">{query.data?.drops?.map((drop) => <div className="dashboard-row" key={drop.slug}><div className="drop-icon"><ShieldCheck size={17} /></div><div className="dashboard-row-info"><strong>{drop.title}</strong><span>{drop.slug} · expires {new Date(drop.expiresAt).toLocaleString()}</span></div><span className={`status-badge ${drop.status.toLowerCase()}`}>{drop.status}</span><button className="row-action" onClick={() => { navigator.clipboard?.writeText(`${window.location.origin}/drop/${drop.slug}`); toast.success("Secure link copied"); }}><Copy size={15} /></button>{drop.status === "ACTIVE" && <button className="row-action danger" aria-label={`Revoke ${drop.title}`} onClick={() => revoke.mutate({ slug: drop.slug })}><Trash2 size={15} /></button>}</div>)}{!query.data?.drops?.length && <div className="dashboard-empty"><ShieldCheck size={23} /><strong>{query.data?.cookieClearedWarning ? "This browser history is unavailable" : "No drops match this view"}</strong><span>{query.data?.cookieClearedWarning ? "The history cookie may have been cleared. Existing links still work for recipients, but this browser cannot recover the ledger." : "Create a drop or clear the filters to see your lifecycle ledger."}</span></div>}</div></div></main>;
}
